export const projects = {
  goldmine: {
    title: 'Goldmine',
    subtitle:
      'Goldmine is a seller support application that accelerates sales through AI, technology, and tradecraft',
    icon: '/images/goldmine-logo-icon.png',
    problem:
      'When IBM sellers are building contact lists on Linkedin Sales Navigator (LISN) there are multiple filters and options but have no way to know what filters give them a targeted list for their product without experience.',
    solution:
      'Goldmine aids sellers by providing tested filters made by experts in their brands to create a focused list of clients who are most likely to be interested in the specific product. it then helps further by increases your connection rate in that list by using proven message frameworks for different scenarios including first touch, follow-up and more.',
    techStack: [
      'Angular',
      'Node.js',
      'Nest.js',
      'MongoDB',
      'AI',
      'LLM',
      'Microsoft Copilot',
    ],

    features: [
      {
        title: 'Prompt Miner',
        src: 'images/prompt-miner.png',
        description:
          "Goldmine's AI prompt builder lets users select filters such as prompt type, industry, and product to auto-generate tailored outreach messages. Users can edit, save favorite prompts to their profile, and use them in any chat platform or directly in Microsoft Copilot.",
      },
      {
        title: 'Goldmine Gems',
        src: 'images/goldmine-gems.png',
        description:
          'Goldmine Gems uses a lean-canvas approach to display product data in easily digestible sections such as: Elevator Pitch, Pain Points, and Target Personas. this equips sellers with quick, actionable insights to boost sales effectiveness.',
      },
      {
        title: 'LISN Personas',
        src: 'images/LISN-personas.png',
        description:
          'Streamlines sales pipeline creation by providing vetted, expert-crafted prompts for targeted outreach. Users select their product category, receive proven prompts, and input them into LISN to identify high-potential prospects. This transforms a complex, time-intensive process into a simple 3-click workflow accessible to new sellers.',
      },
      {
        title: 'Message Generator',
        src: 'images/goldmine-msg-gen.png',

        description:
          'Leverages proven message templates as a base then uses browser-based LLM to analyze the LinkedIn profiles of potential buyers, extracting relevant information to generate personalized outreach messages instantly.',
      },
    ],

    contribution: [
      {
        title: 'Full-Stack Development & Architecture',
        description: [
          'Architected and developed complete initial application from ground up using Angular frontend and Node.js/Nest.js backend',
          "Leveraged Angular's component-based architecture to build responsive, maintainable UI with clear separation of concerns",
          "Utilized Nest.js's modular structure to create scalable API endpoints and implement robust data management patterns",
          'Ensured seamless full-stack integration through proficiency in TypeScript, RESTful API design, and state management',
        ],
      },
      {
        title: 'Technical Leadership & Product Management',
        description: [
          'Transitioned from sole developer to technical lead role, balancing hands-on development with team coordination',
          'Managed product roadmap and feature prioritization, breaking down complex requirements into actionable tasks',
          "Delegated tasks strategically based on team members' skills and development capacity",
        ],
      },
      {
        title: 'User-Centered Development',
        description: [
          'Established direct feedback loops with end users through multiple channels and regular collaborative meetings',
          'Gathered requirements and translated user needs into technical specifications',
          'Facilitated stakeholder discussions to align development roadmap with actual user pain points',
          'Fostered culture of user-centered development across the team',
        ],
      },
      {
        title: 'Key Skills Applied',
        description: [
          'Software architecture, full-stack development (Angular, Node.js, Nest.js, TypeScript)',
          'RESTful API design and backend systems',
          'Agile project management and sprint planning',
          'User research and stakeholder management',
          'Technical leadership and team mentorship',
        ],
      },
    ],

    result: [
      'Enabled new sellers to achieve lead generation effectiveness comparable to experienced team members from day one',
      'Significantly reduced learning curve and accelerated time-to-productivity for new hires',
      'Improved size and quality of lead lists generated by 40%',
      'Strong adoption rates and frequency of use indicating genuine value delivery',
      'Consistent positive feedback on efficiency improvements across the team',
      'Demonstrated leveling effect that elevated new seller performance',
      'Achieved core objectives of streamlining workflows and improving overall team capability',
    ],
  },

  steve: {
    title: 'Steve',
    subtitle:
      'Steve is a custom CMS, designed to expedite and manage deliverables across Global Sales Enablement',
    icon: '/images/Steve_Steve.png',
    problem:
      "Ibm Sales Enablement needed a way to organize, display and filter badges and courses that they've created. additionally they needed an automated process to track the status of the records and what stage of the lifecycle its in. Steve does this and additionally requests information from Your Learning to gather additional information such as ratings, comments and completions.",
    solution:
      'Steve acts as the central location and CMS for all of the information, connecting to multiple data sources, providing clear and concise update and displays. it also provides a detailed filtering system so users can always find exactly the information they need ',
    techStack: [
      'Angular',
      'Node.js',
      'Nest.js',
      'MongoDB',
      'Slack Bot integration',
      'IBM OAuth',
    ],

    features: [
      {
        title: 'Content Library',
        src: 'images/content-library.png',
        description:
          "Steve's Content Library system featuring a customizable table view with adjustable headers and detailed filtering options. Users can toggle between different content types and tailor filters to their workflow preferences.",
      },
      {
        title: 'Customizable Workflow',
        src: 'images/workflow.png',
        description:
          'Multi-step workflow system for creating and updating records with optional approver notifications at chosen key stages. it Tracks progress throughout the process, enabling users to pause and resume work seamlessly.',
      },
      {
        title: 'Persona Selection',
        src: 'images/persona-selector.png',
        description:
          ' Persona system provides role-based access to different Steve workspaces, with separate permissions and access per team. Enabling multi-team collaboration while maintaining appropriate access controls and expanding the scope of Steve beyond enablement.',
      },
      {
        title: 'Calendar View',
        src: 'images/calendar.png',

        description:
          'Interactive calendar view displaying upcoming releases and key dates with real-time record data. Features drag-and-drop functionality for quick date updates.',
      },
    ],

    contribution: [
      {
        title: 'Multi-Step Workflow System',
        description: [
          'Designed and implemented configurable workflow form supporting multiple sequential steps',
          'Built step-specific approval system with customizable approver groups',
          'Integrated Slack notifications for real-time workflow updates',
          'Managed complex state management and error handling while maintaining intuitive user experience',
          'Identified common business process patterns and translated them into reusable technical solutions',
        ],
      },
      {
        title: 'Multi-Persona Platform Architecture',
        description: [
          'Abstracted application architecture to support multiple "personas" for different business units',
          'Transformed single-purpose tool into scalable multi-tenant platform',
          'Enabled departments to leverage core record management capabilities while maintaining unique workflows',
          'Designed thoughtful API structure with data isolation strategies for secure multi-tenancy',
          'Built flexible configuration layer balancing customization with long-term maintainability',
        ],
      },
      {
        title: 'Full-Stack Ownership',
        description: [
          'Took ownership of substantial frontend and backend development across the project',
          'Demonstrated architectural thinking by building systems that extended value organization-wide',
          'Created scalable, reusable solutions that supported growth beyond initial use case',
        ],
      },
      {
        title: 'Key Skills Applied',
        description: [
          'Software architecture and system design',
          'API design and data isolation strategies',
          'Workflow orchestration and state management',
          'Cross-functional integration and multi-tenant architecture',
          'Modular, scalable code patterns',
        ],
      },
    ],

    result: [
      'Transformed single-team tool into enterprise-wide multi-tenant platform through flexible architecture',
      'Achieved 10x expansion in user base through scalable technical foundation',
      'Workflow architecture proved versatile enough to accommodate diverse business use cases, with teams having average 3 workflows per persona',
      'Created foundation that enabled organizational growth without requiring fundamental rebuilds',
    ],
  },

  ultraphone: {
    title: 'Events App/Ultraphone',
    subtitle:
      'The Events app provided a live event experience for over 20 000 users with ultraphone providing live interactions and notifications to enhance the experience. ',
    icon: './images/sko_logo.png',
    problem:
      "IBM's sales teams relied on a third-party platform called Megaphone for interactive event experiences. While it served its purpose, the platform came with high recurring costs and limited customization options. Over four years, it accumulated more than $240K in expenses and required additional contracted support just to meet internal needs. The team needed an in-house solution that was more flexible, scalable, and cost-effective without compromising user experience.",
    solution:
      'Steve acts as the central location and CMS for all of the information, connecting to multiple data sources, providing clear and concise update and displays. it also provides a detailed filtering system so users can always find exactly the information they need ',
    techStack: [
      'React',
      'Carbon Components',
      'Redis',
      'Pub Sub',
      'Node.js',
      'Nest.js',
      'MongoDB',
      'IBM OAuth',
    ],

    features: [
      {
        title: 'Interaction Playlist',
        src: 'images/interaction-playlist.png',
        description:
          'Event management interface displaying interaction playlists with real-time status tracking. Admins can manually control or schedule event start/stop times using preset timers, with visibility into current interactions and session progress.',
      },
      {
        title: 'Interaction Display',
        src: 'images/interaction-display.png',
        description:
          'Event viewer featuring video playback with session details (title,speakers, descriptions) and an integrated chat/interaction panel. Auto-displays admin-submitted interactions with user notifications to drive engagement.',
      },
      {
        title: 'Results Page',
        src: 'images/results-page.png',
        description:
          'Results page displaying user responses organized by interaction type. Features soft delete moderation tools for removing inappropriate content across interaction formats during live event. post-event the page provides a summary of the responses for visualization',
      },
      {
        title: 'Interaction Dashboard',
        src: 'images/interaction-dashboard.png',

        description:
          'Admin dashboard for building and managing event interaction playlists. Features drag-and-drop reordering across multiple events, plus full CRUD capabilities for interactions and their associated information.',
      },
    ],

    contribution: [
      {
        title: 'Dashboard Page Design & Implementation',
        description: [
          'Created initial UI and dashboard page from ground up',
          'Provided clear, comprehensive display of all planned event interactions',
          'Enabled quick creation, editing, and rearrangement of interactions with no coding knowledge required',
          'Focused on intuitive user experience for non-technical users',
        ],
      },
      {
        title: 'Results Page Implementation',
        description: [
          'Built dual-function results page for post-event analysis and management',
          'Developed display system for all user responses organized and sorted by interaction type',
          'Implemented soft delete functionality for inappropriate or unrelated user responses across various interaction formats (word clouds, leaderboards, etc.)',
          'Created efficient data management tools for live moderation of displayed content',
        ],
      },
      {
        title: 'Leaderboard Implementation',
        description: [
          'Created MongoDb aggregation to gather all user responses, add all scores of single user and display the top participants',
          'Optimized Database operation to handle calculations on large dataset for live event.',
          'Created Abstracted display component to show leaderboard results with customizable length.',
        ],
      },
      {
        title: 'Key Skills Applied',
        description: [
          'Frontend development with focus on usability and accessibility',
          'No-code interface design for non-technical event planners',
          'Data visualization and management systems',
        ],
      },
    ],

    result: [
      'Saved IBM up to $500K by replacing a third-party event platform with a scalable, in-house React solution.',
      'Reduced integration maintenance costs associated with external systems',
      'Addressed critical pain points inherent in vendor solution',
      'Resolved issues with limited flexibility and Improved integration capabilities across internal systems',
      'Delivered greater control and customization aligned with business needs',
    ],
  },
};
